### ISSUE TITLE
Make it a real device

### ISSUE THREAD

**Issue by jjtbsomhorst** [DiedB/it.diederik.wol#3]
Hi, 

Currently when I want to turn on my pc using the new Homey beta phone app I have to tab the device and next I have to tab the 'press' button to turn it on. It would be nice to have it act like a real device like for instance a light where the on/of switch is next to the name in the list of devices.

**Comment by DiedB** [comment]
This is a limitation of the WOL protocol. I can only turn the PC on remotely, turning it off or getting the current status is not possible. Those two things are needed to implement a switch instead of a button.

**Comment by jjtbsomhorst** [comment]
I know that you can't turn things of with wol ( thats what the O stands for in wol ;)). But it would be nice to have it work like a real device. Can't you make a 'fake' off function?

**Comment by DiedB** [comment]
I can, but that would be a bad practice. This is already a real device,
with a different class from lamps for example, which have the slider. I
don't want users to have to press the switch two times every time they want
to power on their device (that would be the result of your suggestion).

You should make an issue in the Homey issues repository instead, and give
the suggestion to make the button also easily accessible from the app.
