### ISSUE TITLE
Device added, but didn’t wake up

### ISSUE THREAD

**Issue by miszterx** [DiedB/it.diederik.wol#6]
Hi, i have a homey pro with firmware 7.1.6.
I have your app with 3.0.3 version.

i can add devices and it shows up in the devices list. I press the button to wake up, but nothing happen :(

i tried with two machines and i have a rpi where i can send the wol as well. It worked, but didn’t work from homey.

can you help?
Thanks!

**Comment by DiedB** [comment]
Is the Homey in the same subnet as the Raspberry Pi? Given that Homey is on WiFi and the Pi is on ethernet, that might cause a difference in how network traffic is handled.

It is pretty difficult to debug Wake on LAN, if you're sure your configuration works you'll have to start debugging with packet captures and see if packets from Homey actually reach the devices you want to turn on.

**Comment by miszterx** [comment]
Originally it was in different subnet. I have a WLAN and  LAN subnet. Homey was in the WLAN and all the other machines (2 x wol devices and rpi) are in the LAN.
So I have changed and now all of them in the same subnet. 
Unfortunately it didn't work.

Shall I power on one of the WOL device and run a network package capture to see if the WOL package arrive at all? (probably not and this is why it didn't wake up).
Or is there any homey based troubleshoot what can help to see if it send the package at all?

**Comment by DiedB** [comment]
I would say, connect a device to the WLAN network and try sending magic packets from there. That might help get you started.

The Homey is definitely sending the package, otherwise there would be lots of users complaining here ;-)
