### ISSUE TITLE
Wake on lan with google assistant/home via homey

### ISSUE THREAD

**Issue by ajugland** [DiedB/it.diederik.wol#7]
Is this possible or do i need to use the homey app. I want voice control via this

**Comment by DiedB** [comment]
This will never be the responsibility of this app - you could look at using Homey Flow to reach your goal.

**Comment by ajugland** [comment]
Thanks

Best regards,

*André Jørgen Ugland*

E-mail:                     ***@***.***
Phone:                     97047714

___________________________________________________________
Address: Håvundvegen 22, 3715 Skien
